name = "gnk-asg-auto-editor-public-clean"
main = "src/index.js"
compatibility_date = "2026-06-17"
workers_dev = true
preview_urls = true

# Nema produkcijskih ruta.
# Jedini vlasnik /auto-editor* ruta je gnk-asg-auto-editor-worker.