import {prepareAiAutoReply,VERSION as AI_REPLY_VERSION} from '../../gnk-asg-direct-operator/src/ai-inbound-auto-reply-v2.js';

const VERSION=`GNK_ASG_MAIL_CENTER_PROFILE_PARITY_V4_20260703_${AI_REPLY_VERSION}`;
const COPY='rht@gmx.com',MAX=250;
const PROFILES={
 office:{id:'office',email:'office@gnk-asg.hr',name:'GNK ASG Office',unit:'Office'},
 info:{id:'info',email:'info@gnk-asg.hr',name:'GNK ASG Information Desk',unit:'General Information'},
 sefic:{id:'sefic',email:'sefic@gnk-asg.hr',name:'Nermin Sefić | Executive Office',unit:'Executive Office'},
 ubo:{id:'ubo',email:'ubo@gnk-asg.hr',name:'GNK DINAMO Ltd. Group | UBO Office',unit:'UBO Office',group:true},
 press:{id:'press',email:'press@gnk-asg.hr',name:'GNK DINAMO Ltd. Group | Press Office',unit:'Press Office',group:true,media:true},
 assistant:{id:'assistant',email:'assistant@gnk-asg.hr',name:'GNK ASG | Executive Assistant',unit:'Executive Assistant'},
 media:{id:'media',email:'media@gnk-asg.hr',name:'GNK DINAMO Ltd. Group | Media Relations & Accreditation Center',unit:'Media Relations & Accreditation Center',group:true,media:true},
 legal:{id:'legal',email:'legal@gnk-asg.hr',name:'GNK ASG Legal & Compliance',unit:'Legal & Compliance',legal:true},
 privacy:{id:'privacy',email:'privacy@gnk-asg.hr',name:'GNK ASG Privacy Office',unit:'Privacy & Data Protection',privacy:true},
 it:{id:'it',email:'it@gnk-asg.hr',name:'GNK ASG IT | Digital Assistant',unit:'IT & Digital Support'},
 contact:{id:'contact',email:'contact@gnk-asg.hr',name:'GNK ASG Contact Centre',unit:'General Contact'},
 director:{id:'director',email:'nermin.sefic@gnk-asg.hr',name:'Nermin Sefić | Managing Director',unit:'Managing Director'}
};
const BY_EMAIL=new Map(Object.values(PROFILES).map(p=>[p.email,p]));
const clean=v=>String(v??'').trim();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const header=(m,n)=>{try{return clean(m?.headers?.get?.(n));}catch{return'';}};
const email=v=>(String(v??'').match(/[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}/i)?.[0]||'').toLowerCase();
const profile=v=>BY_EMAIL.get(email(v))||PROFILES.assistant;
const split=v=>[...new Set((Array.isArray(v)?v:String(v??'').split(/[;,\s]+/)).map(x=>clean(x).toLowerCase()).filter(Boolean))];
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'https://gnk-asg.hr','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-gnk-asg-token'}});
function ref(prefix){const d=new Date(),p=n=>String(n).padStart(2,'0');return`${prefix}-${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}-${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;}
async function read(env,key){try{const raw=await env.GNK_ASG_KV?.get(key),value=raw?JSON.parse(raw):[];return Array.isArray(value)?value:[];}catch{return[];}}
async function log(env,key,item){if(!env.GNK_ASG_KV)return;const items=await read(env,key);await env.GNK_ASG_KV.put(key,JSON.stringify([item,...items.filter(x=>x?.id!==item?.id)].slice(0,MAX),null,2));}
async function claim(env,id,fallback){if(!env.GNK_ASG_KV)return true;const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(clean(id||fallback))),hash=[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join(''),key=`mail:inbound:dedupe:${hash}`;if(await env.GNK_ASG_KV.get(key))return false;await env.GNK_ASG_KV.put(key,new Date().toISOString(),{expirationTtl:604800});return true;}
function automated(m,s){const a=header(m,'auto-submitted').toLowerCase(),p=header(m,'precedence').toLowerCase(),x=header(m,'x-auto-response-suppress'),u=header(m,'subject').toLowerCase();return Boolean((a&&a!=='no')||/bulk|list|junk/.test(p)||x||/mailer-daemon|postmaster|no-?reply|donotreply/.test(s)||/automatic reply|auto reply|out of office|izvan ureda|undeliverable|delivery status notification/.test(u));}
function disclaimer(p){if(p.media)return'Ova potvrda nije odobrenje akreditacije, najava objave, prihvat ponude, ugovorna obveza niti konačna odluka. / This acknowledgement is not an accreditation approval, publication commitment, acceptance of an offer, contractual commitment or final decision.';if(p.privacy)return'Ova potvrda ne predstavlja provjeru identiteta, prihvat zahtjeva ispitanika niti konačnu odluku. / This acknowledgement does not constitute identity verification, acceptance of a data-subject request or a final decision.';if(p.legal)return'Ova potvrda ne predstavlja prihvat ponude, priznanje odgovornosti, odricanje od prava, pravno mišljenje niti konačnu odluku. / This acknowledgement does not constitute acceptance of an offer, admission of liability, waiver of rights, legal advice or a final decision.';return'Ova potvrda ne predstavlja prihvat ponude, ugovornu obvezu, pravno mišljenje niti konačnu odluku. / This acknowledgement does not constitute acceptance of an offer, a contractual commitment, legal advice or a final decision.';}
function body(p,id,subject){const s=clean(subject)||'(no subject)';return`Poštovani,\n\npotvrđujemo da je Vaša poruka zaprimljena na adresi ${p.email} (${p.unit}) pod evidencijskim brojem ${id}.\n\nIzvorni predmet: ${s}\n\nPoruka je evidentirana i proslijeđena nadležnoj osobi na ljudski pregled. ${disclaimer(p)}\n\nU daljnjoj komunikaciji navedite gornji evidencijski broj.\n\n--- ENGLISH ---\n\nDear Sir or Madam,\n\nThis confirms that your message has been received at ${p.email} (${p.unit}) under reference ${id}.\n\nOriginal subject: ${s}\n\nThe message has been recorded and routed to the responsible person for human review. ${disclaimer(p)}\n\nPlease quote the reference above in further correspondence.`;}
function signatureText(p){return[p.name,p.unit,p.email,'https://gnk-asg.hr'].join('\n');}
function signatureHtml(p){const logo=p.group?'https://gnk-asg.hr/assets/gnk-group-email-logo-final.png':'https://gnk-asg.hr/assets/gnk-asg-email-logo-final.png';return`<table data-gnk-asg-signature="${VERSION}" role="presentation" cellpadding="0" cellspacing="0" border="0" style="font-family:Arial,Helvetica,sans-serif;border-collapse:collapse;margin-top:22px;max-width:720px;width:100%;border-top:1px solid #d9d9d9"><tr><td width="170" valign="top" style="width:170px;padding:18px 22px 8px 0"><img src="${logo}" width="150" alt="${esc(p.name)}" style="display:block;width:150px;max-width:150px;height:auto;border:0"></td><td valign="top" style="padding:18px 0 8px;color:#111827;font-size:14px;line-height:1.45"><div style="font-size:20px;font-weight:700;color:#0b223d;margin-bottom:5px">${esc(p.name)}</div><div style="font-weight:700;color:#0b223d;margin-bottom:5px">${esc(p.unit)}</div><div><strong>E:</strong> <a href="mailto:${esc(p.email)}">${esc(p.email)}</a></div><div><strong>W:</strong> <a href="https://gnk-asg.hr">https://gnk-asg.hr</a></div></td></tr></table>`;}
function html(text,p){return`<div style="font-family:Arial,Helvetica,sans-serif;color:#111827;font-size:15px;line-height:1.55">${text.split('\n').map(x=>x?esc(x):'<br>').join('<br>')}${signatureHtml(p)}</div>`;}
function strip(v){return clean(v).replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+\n/g,'\n').trim();}
function attachments(input){let total=0;return(Array.isArray(input)?input:[]).map(item=>{const filename=clean(item?.filename||item?.name||'document.pdf'),type=clean(item?.type||'application/pdf');let b64=clean(item?.base64||item?.content||'').replace(/^data:[^;,]+;base64,/i,'').replace(/\s+/g,'').replace(/-/g,'+').replace(/_/g,'/');while(b64.length%4)b64+='=';const binary=atob(b64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);total+=bytes.length;if(bytes.length>3200000||total>3400000)throw new Error('Attachment size limit exceeded');return{filename,type,content:bytes.buffer,disposition:'attachment'};});}
async function send(request,env){let d;try{d=await request.json();}catch{return json({ok:false,error:'invalid_json'},400);}const p=profile(d.from||d.profile),to=split(d.to),cc=split(d.cc),bcc=[...new Set([...split(d.bcc),COPY])],subject=clean(d.subject),rawHtml=clean(d.html||d.bodyHtml||d.body||''),rawText=clean(d.text||d.plainText||strip(rawHtml)),signedText=`${rawText}\n\n${signatureText(p)}`,signedHtml=`${rawHtml||`<div>${esc(rawText)}</div>`}${signatureHtml(p)}`;if(!to.length||!subject||!rawText)return json({ok:false,error:'missing_required_field'},400);let files;try{files=attachments(d.attachments);}catch(e){return json({ok:false,error:String(e?.message||e)},400);}const id=ref('GNK-SEND'),record={id,createdAt:new Date().toISOString(),profile:p.id,from:{email:p.email,name:p.name},to,cc,bcc,subject,attachmentCount:files.length,status:'sending'};await log(env,'mail:outbox',record);if(!env.EMAIL?.send)return json({ok:false,error:'EMAIL binding missing'},501);try{const r=await env.EMAIL.send({to:to.length===1?to[0]:to,cc:cc.length?(cc.length===1?cc[0]:cc):undefined,bcc:bcc.length===1?bcc[0]:bcc,from:{email:p.email,name:p.name},replyTo:p.email,subject,text:signedText,html:signedHtml,attachments:files});const sent={...record,status:'sent',messageId:clean(r?.messageId)||null};await log(env,'mail:sent',sent);return json({ok:true,sent:true,record:sent});}catch(e){const failed={...record,status:'send_failed',error:String(e?.message||e)};await log(env,'mail:sent',failed);return json({ok:false,error:failed.error,record:failed},500);}}
async function inbound(message,env){const fromRaw=message?.from||header(message,'from'),sender=email(header(message,'reply-to')||fromRaw),p=profile(message?.to||header(message,'to')),subject=header(message,'subject')||'(no subject)',messageId=header(message,'message-id'),id=ref(`GNK-${p.id.toUpperCase()}-IN`),base={id,createdAt:new Date().toISOString(),version:VERSION,from:fromRaw,to:p.email,fromEmail:sender,toEmail:p.email,subject,messageId,profile:p.id,status:'received'};await log(env,'mail:inbox',base);try{await message.forward?.(COPY,new Headers({'X-GNK-ASG-Original-Recipient':p.email,'X-GNK-ASG-Routing-Profile':p.id}));await log(env,'mail:sent',{...base,status:'incoming_forward_sent'});}catch(e){await log(env,'mail:sent',{...base,status:'incoming_forward_failed',error:String(e?.message||e)});}if(!sender||sender.endsWith('@gnk-asg.hr')||automated(message,sender)||!(await claim(env,messageId,`${sender}|${p.email}|${subject}`)))return;if(!env.EMAIL?.send)return;const content=body(p,id,subject),replySubject=/^re:/i.test(subject)?subject:`Re: ${subject}`,out={...base,status:'auto_reply_sending',autoReplyTo:sender};await log(env,'mail:outbox',out);try{const r=await env.EMAIL.send({to:sender,bcc:COPY,from:{email:p.email,name:p.name},replyTo:p.email,subject:replySubject,text:`${content}\n\n${signatureText(p)}`,html:html(content,p),headers:{'Auto-Submitted':'auto-replied','X-Auto-Response-Suppress':'All','X-GNK-ASG-Mail-Center':VERSION,'X-GNK-ASG-Receipt':id,'X-GNK-ASG-Profile':p.id}});await log(env,'mail:sent',{...out,status:'auto_reply_sent',messageId:clean(r?.messageId)||null});}catch(e){await log(env,'mail:sent',{...out,status:'auto_reply_failed',error:String(e?.message||e)});}}
function preview(url){const p=profile(url.searchParams.get('to')),id=ref(`GNK-${p.id.toUpperCase()}-PREVIEW`),subject=clean(url.searchParams.get('subject')||'Controlled test'),content=body(p,id,subject);return json({ok:true,version:VERSION,profile:p,receipt:id,subject,text:`${content}\n\n${signatureText(p)}`,html:html(content,p)});}
export default{async fetch(request,env){if(request.method==='OPTIONS')return new Response(null,{status:204});const url=new URL(request.url),path=url.pathname.replace(/\/+$/,'')||'/';if(path==='/api/admin-mail-send'&&request.method==='POST')return send(request,env);if(path==='/api/mail-center/status')return json({ok:true,version:VERSION,service:'GNK ASG Mail Center',emailBinding:Boolean(env.EMAIL),aiBinding:Boolean(env.AI),autoReply:true,signatures:true,profiles:Object.values(PROFILES),mandatoryBcc:COPY,time:new Date().toISOString()});if(path==='/api/mail-center/auto-reply-preview')return preview(url);if(path==='/api/mail-center/inbox')return json({ok:true,items:await read(env,'mail:inbox')});if(path==='/api/mail-center/sent')return json({ok:true,items:await read(env,'mail:sent')});if(path==='/api/mail-center/outbox')return json({ok:true,items:await read(env,'mail:outbox')});return json({ok:false,error:'not_found',path},404);},async email(message,env,ctx){const prepared=prepareAiAutoReply(message,env),task=inbound(prepared.message,prepared.env);if(ctx?.waitUntil){ctx.waitUntil(task);return;}return task;}};
