import { EDITORIAL_SOURCES, EDITORIAL_SOURCE_VERSION } from './editorial-sources-v1.js';

export const EDITORIAL_VERSION='GNK_ASG_EDITORIAL_CENTER_V1_20260624';
const MODEL='@cf/meta/llama-3.1-8b-instruct-fast';
const AUTHOR='Nermin Sefić';
const MIN_WORDS={analysis:500,news:500,announcement:150,press:150};
const IMAGE_SETS=['financije-poslovanje','tehnologija-ai','globalno-poslovanje','digitalna-imovina-fintech-trzista','infrastruktura-sport-odrzivost'];

const clean=value=>String(value??'').trim();
const words=value=>clean(value).split(/\s+/).filter(Boolean).length;
const nowIso=()=>new Date().toISOString();
const store=env=>env.GNK_ASG_KV||env.GNK_ASG_CONFIG_KV||null;

export function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0','x-gnk-asg-editorial':EDITORIAL_VERSION}});}

async function readJson(env,key,fallback){const kv=store(env);if(!kv)return fallback;try{const raw=await kv.get(key);return raw?JSON.parse(raw):fallback;}catch{return fallback;}}
async function writeJson(env,key,value,ttl){const kv=store(env);if(!kv)return false;await kv.put(key,JSON.stringify(value,null,2),ttl?{expirationTtl:ttl}:undefined);return true;}
async function readList(env,key){const value=await readJson(env,key,[]);return Array.isArray(value)?value:[];}
async function writeList(env,key,value,max=500){return writeJson(env,key,value.slice(0,max));}

function slugify(value){return clean(value||'objava').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,110)||'objava';}
function decodeXml(value){return String(value||'').replace(/<!\[CDATA\[/g,'').replace(/\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}
function tag(block,name){const match=String(block||'').match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'));return match?decodeXml(match[1]):'';}
function itemLink(block){return tag(block,'link')||decodeXml((String(block||'').match(/<link[^>]+href=["']([^"']+)["']/i)||[,''])[1]);}
function parseFeed(xml,source){const blocks=String(xml||'').match(/<item[\s\S]*?<\/item>/gi)||String(xml||'').match(/<entry[\s\S]*?<\/entry>/gi)||[];return blocks.slice(0,20).map((block,index)=>{const title=clean(tag(block,'title'));const url=itemLink(block);const publishedAt=tag(block,'pubDate')||tag(block,'published')||tag(block,'updated')||nowIso();return{id:`source-${source.id}-${index}-${slugify(title).slice(0,45)}`,title,summary:clean(tag(block,'description')||tag(block,'summary')||tag(block,'content')).slice(0,900),url,sourceUrl:url,source:source.name,sourceId:source.id,category:source.category,group:source.category,region:source.market,publishedAt,published_at:publishedAt};}).filter(item=>item.title&&/^https?:\/\//i.test(item.url));}

async function fetchCandidate(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{signal:controller.signal,headers:{'user-agent':'GNK-ASG-Editorial-Center/1.0',accept:'application/rss+xml,application/atom+xml,application/xml,text/xml,*/*'}});const body=await response.text();return{ok:response.ok,status:response.status,body,contentType:response.headers.get('content-type')||''};}catch(error){return{ok:false,status:0,body:'',error:clean(error?.message||error)};}finally{clearTimeout(timer);}}

async function fetchSource(source){const attempts=[];for(const feedUrl of source.feeds||[]){const result=await fetchCandidate(feedUrl);const items=result.ok?parseFeed(result.body,source):[];attempts.push({feedUrl,status:result.status,ok:result.ok,itemCount:items.length,error:result.error||null});if(result.ok&&items.length)return{ok:true,sourceId:source.id,name:source.name,homepage:source.homepage,feedUrl,status:result.status,items,attempts};}return{ok:false,sourceId:source.id,name:source.name,homepage:source.homepage,feedUrl:null,status:attempts.at(-1)?.status||0,items:[],attempts};}

export async function refreshBusinessSources(env){const startedAt=nowIso();const results=await Promise.all(EDITORIAL_SOURCES.map(fetchSource));const seen=new Set();const items=results.flatMap(result=>result.items).filter(item=>{const key=clean(item.url).toLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>Date.parse(b.publishedAt||0)-Date.parse(a.publishedAt||0)).slice(0,250);const payload={ok:items.length>0,version:EDITORIAL_VERSION,sourceVersion:EDITORIAL_SOURCE_VERSION,status:items.length?'LIVE':'FALLBACK',startedAt,updatedAt:nowIso(),count:items.length,healthySources:results.filter(result=>result.ok).length,totalSources:results.length,sources:results.map(({items:sourceItems,...rest})=>({...rest,itemCount:sourceItems.length})),items};await writeJson(env,'editorial:sources:last',payload);await writeList(env,'editorial:news:items',items,500);await writeJson(env,'data:news:external',{ok:true,status:payload.status,updatedAt:payload.updatedAt,count:payload.count,sources:results.filter(result=>result.ok).map(result=>result.name),errors:results.filter(result=>!result.ok).map(result=>({source:result.name,attempts:result.attempts})),items});await writeJson(env,'automation:news-refresh:last',{ok:payload.ok,status:payload.status,updatedAt:payload.updatedAt,count:payload.count,healthySources:payload.healthySources,totalSources:payload.totalSources,schedule:'09:00 and 16:00 Europe/Zagreb'});return payload;}

function chooseImage(seed,category){const haystack=`${category} ${seed}`.toLowerCase();let set='globalno-poslovanje';if(/ai|tech|digital|software|cyber/.test(haystack))set='tehnologija-ai';else if(/market|financ|bank|capital|econom|poslov/.test(haystack))set='financije-poslovanje';else if(/bitcoin|crypto|fintech|payment|burz/.test(haystack))set='digitalna-imovina-fintech-trzista';else if(/sport|energy|green|sustain|infrastr/.test(haystack))set='infrastruktura-sport-odrzivost';if(!IMAGE_SETS.includes(set))set=IMAGE_SETS[0];const hash=[...String(seed||'')].reduce((sum,char)=>(sum*31+char.charCodeAt(0))>>>0,0);const number=String((hash%20)+1).padStart(3,'0');return`/assets/seo-gallery/gnk-asg-${set}-${number}.jpg`;}

function draftId(){return`draft-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;}
function normalizeSources(value){if(Array.isArray(value))return value.map(item=>({title:clean(item?.title),url:clean(item?.url),source:clean(item?.source)})).filter(item=>item.url);return clean(value).split(/\n+/).map(line=>{const parts=line.split(/\s+\|\s+/);return{title:clean(parts[0]),url:clean(parts[1]||parts[0]),source:clean(parts[2])};}).filter(item=>/^https?:\/\//i.test(item.url));}

export function normalizeDraft(input,existing={}){const now=nowIso();const contentType=['analysis','news','announcement','press'].includes(clean(input.contentType))?clean(input.contentType):'analysis';const titleHr=clean(input.titleHr||input.title);const titleEn=clean(input.titleEn);const slug=slugify(input.slug||titleHr||titleEn||existing.slug);return{...existing,id:clean(input.id||existing.id)||draftId(),kind:'article',type:'article',contentType,status:'draft',approvedForPublic:false,slug,title:titleHr,titleHr,titleEn,summary:clean(input.summaryHr||input.summary),summaryHr:clean(input.summaryHr||input.summary),summaryEn:clean(input.summaryEn),body:clean(input.bodyHr||input.body),bodyHr:clean(input.bodyHr||input.body),bodyEn:clean(input.bodyEn),category:clean(input.category||'business'),region:clean(input.region||'world'),image:clean(input.image)||chooseImage(`${titleHr}-${slug}`,input.category),imageAlt:clean(input.imageAlt)||`${titleHr||'GNK ASG analiza'} — GNK ASG Visual Index`,imageCredit:'GNK ASG Visual Index',author:clean(input.author)||AUTHOR,source:'GNK ASG Editorial Center',sourceUrl:clean(input.sourceUrl),sources:normalizeSources(input.sources),notes:clean(input.notes),createdAt:existing.createdAt||now,updatedAt:now,seo:{titleHr:clean(input.seoTitleHr||titleHr).slice(0,75),titleEn:clean(input.seoTitleEn||titleEn).slice(0,75),descriptionHr:clean(input.seoDescriptionHr||input.summaryHr||input.summary).slice(0,170),descriptionEn:clean(input.seoDescriptionEn||input.summaryEn).slice(0,170),keywords:Array.isArray(input.keywords)?input.keywords.map(clean).filter(Boolean).slice(0,24):clean(input.keywords).split(',').map(clean).filter(Boolean).slice(0,24),author:AUTHOR}};}

export async function listDrafts(env){return readList(env,'editorial:drafts');}
export async function saveDraft(env,input){const drafts=await listDrafts(env);const existing=drafts.find(item=>item.id===input.id)||{};const draft=normalizeDraft(input,existing);await writeList(env,'editorial:drafts',[draft,...drafts.filter(item=>item.id!==draft.id)],500);await writeJson(env,`editorial:draft:${draft.id}`,draft);return{ok:true,draft};}
export async function deleteDraft(env,id){const drafts=await listDrafts(env);const remaining=drafts.filter(item=>item.id!==id);await writeList(env,'editorial:drafts',remaining,500);return{ok:remaining.length!==drafts.length,id};}

async function aiText(env,system,prompt,maxTokens=4096,temperature=0.2){if(!env.AI?.run)throw new Error('AI_binding_missing');const result=await env.AI.run(env.AUTO_EDITOR_MODEL||MODEL,{messages:[{role:'system',content:system},{role:'user',content:prompt}],max_tokens:maxTokens,temperature});return clean(result?.response||result?.result?.response||result?.output_text||result?.text||'').replace(/^```(?:json|markdown|text)?/i,'').replace(/```$/,'').trim();}
function extractJson(value){const start=String(value).indexOf('{');const end=String(value).lastIndexOf('}');if(start<0||end<=start)throw new Error('metadata_json_missing');return JSON.parse(String(value).slice(start,end+1));}
async function longBody(env,language,title,sourceContext){const hr=language==='hr';let body='';for(let attempt=0;attempt<4&&words(body)<560;attempt+=1){const prompt=body?`${hr?'Nastavi članak na hrvatskom':'Continue the article in English'}. ${hr?'Dodaj 280 do 380 novih riječi, bez ponavljanja, s poslovnim učincima, rizicima, prilikama i zaključkom.':'Add 280 to 380 new words without repetition, covering business implications, risks, opportunities and a conclusion.'}\n\n${body}\n\nSources:\n${sourceContext}`:`${hr?'Napiši izvornu poslovnu analizu na hrvatskom jeziku':'Write an original business analysis in English'} od 420 do 520 riječi. ${hr?'Objasni činjenice, važnost teme, poslovne učinke, europski ili globalni kontekst, rizike, prilike i zaključak.':'Explain the facts, why the topic matters, business implications, European or global context, risks, opportunities and a conclusion.'} Ne izmišljaj činjenice, ne koristi markdown, naslov ni potpis.\n\nTitle: ${title}\nSources:\n${sourceContext}`;const chunk=await aiText(env,hr?'Pišeš profesionalne i činjenične poslovne analize na hrvatskom jeziku.':'You write professional, factual business analysis in English.',prompt,4096,0.24);if(words(chunk)>60)body=body?`${body}\n\n${chunk}`:chunk;}return body.split(/\s+/).slice(0,1200).join(' ');}

export async function generateAiDraft(env,input={}){const news=await readList(env,'editorial:news:items');const sourceItem=input.sourceUrl?news.find(item=>item.url===input.sourceUrl):null;const topic=clean(input.topic||input.titleHr||sourceItem?.title||'Aktualna poslovna tema');const sourceContext=JSON.stringify([{title:sourceItem?.title||input.sourceTitle||topic,summary:sourceItem?.summary||input.notes||'',url:sourceItem?.url||input.sourceUrl||'',source:sourceItem?.source||input.sourceName||'GNK ASG Editorial Center',publishedAt:sourceItem?.publishedAt||nowIso()}]);let metadata={};try{metadata=extractJson(await aiText(env,'Ti si glavni urednik GNK ASG Intelligence Deska.',`Vrati samo JSON s ključevima titleHr,titleEn,summaryHr,summaryEn,category,region,seoTitleHr,seoTitleEn,seoDescriptionHr,seoDescriptionEn,keywords. Sažeci moraju imati 80 do 130 riječi. Ne izmišljaj činjenice.\n\nTema: ${topic}\nBilješke: ${clean(input.notes)}\nIzvor: ${sourceContext}`,1800,0.15));}catch{}
const titleHr=clean(metadata.titleHr||topic);const titleEn=clean(metadata.titleEn||topic);const [bodyHr,bodyEn]=await Promise.all([longBody(env,'hr',titleHr,sourceContext),longBody(env,'en',titleEn,sourceContext)]);if(words(bodyHr)<500||words(bodyEn)<500)throw new Error(`generated_text_too_short_hr_${words(bodyHr)}_en_${words(bodyEn)}`);const saved=await saveDraft(env,{contentType:input.contentType||'analysis',titleHr,titleEn,summaryHr:metadata.summaryHr||bodyHr.slice(0,420),summaryEn:metadata.summaryEn||bodyEn.slice(0,420),bodyHr,bodyEn,category:metadata.category||sourceItem?.category||input.category||'business',region:metadata.region||sourceItem?.region||input.region||'world',sourceUrl:sourceItem?.url||input.sourceUrl,sources:[{title:sourceItem?.title||topic,url:sourceItem?.url||input.sourceUrl||'',source:sourceItem?.source||input.sourceName||''}],seoTitleHr:metadata.seoTitleHr,seoTitleEn:metadata.seoTitleEn,seoDescriptionHr:metadata.seoDescriptionHr,seoDescriptionEn:metadata.seoDescriptionEn,keywords:metadata.keywords,notes:input.notes});return{ok:true,generated:true,draft:saved.draft};}

export async function generateScheduledDraft(env){const items=await readList(env,'editorial:news:items');const history=await readList(env,'editorial:draft-source-history');const used=new Set(history.slice(0,500).map(item=>clean(item.sourceUrl).toLowerCase()));const sourceItem=items.find(item=>!used.has(clean(item.url).toLowerCase()));if(!sourceItem)return{ok:false,error:'no_unused_source'};const result=await generateAiDraft(env,{sourceUrl:sourceItem.url,sourceTitle:sourceItem.title,sourceName:sourceItem.source,notes:sourceItem.summary,category:sourceItem.category,region:sourceItem.region});await writeList(env,'editorial:draft-source-history',[{sourceUrl:sourceItem.url,draftId:result.draft.id,createdAt:nowIso()},...history],1000);return result;}

function firstWords(value,count){return clean(value).split(/\s+/).slice(0,count).join(' ');}
function validation(draft){const errors=[];const minimum=MIN_WORDS[draft.contentType]||500;if(!draft.titleHr||!draft.titleEn)errors.push('missing_titles');if(words(draft.bodyHr)<minimum)errors.push(`hr_body_min_${minimum}`);if(words(draft.bodyEn)<minimum)errors.push(`en_body_min_${minimum}`);if(!draft.image)errors.push('missing_image');if(!draft.sources?.length&&!draft.sourceUrl)errors.push('missing_source');return errors;}

export async function publishDraft(env,id){const drafts=await listDrafts(env);const draft=drafts.find(item=>item.id===id);if(!draft)return{ok:false,error:'draft_not_found'};const errors=validation(draft);if(errors.length)return{ok:false,error:'validation_failed',errors};const now=nowIso();const canonical=`https://gnk-asg.hr/objave/${draft.slug}/`;const sources=draft.sources?.length?draft.sources:[{title:draft.titleHr,url:draft.sourceUrl,source:'Izvor'}];const sourceLinesHr=sources.map((item,index)=>`${index+1}. ${item.source||'Izvor'}: ${item.title||''} – ${item.url}`).join('\n');const sourceLinesEn=sources.map((item,index)=>`${index+1}. ${item.source||'Source'}: ${item.title||''} – ${item.url}`).join('\n');const article={...draft,id:`manual-${now.replace(/[^0-9]/g,'').slice(0,14)}-${draft.slug.slice(0,50)}`,status:'published',approvedForPublic:true,title:draft.titleHr,summary:draft.summaryHr||firstWords(draft.bodyHr,70),summaryHr:draft.summaryHr||firstWords(draft.bodyHr,70),summaryEn:draft.summaryEn||firstWords(draft.bodyEn,70),body:`${draft.bodyHr}\n\nIzvori informacija:\n${sourceLinesHr}\n\nAutor: ${AUTHOR}`,bodyHr:`${draft.bodyHr}\n\nIzvori informacija:\n${sourceLinesHr}\n\nAutor: ${AUTHOR}`,bodyEn:`${draft.bodyEn}\n\nInformation sources:\n${sourceLinesEn}\n\nAuthor: ${AUTHOR}`,author:AUTHOR,source:'GNK ASG Editorial Center',sourceUrl:sources[0]?.url||draft.sourceUrl,createdAt:draft.createdAt,updatedAt:now,publishedAt:now,published_at:now,canonical,hrUrl:`/objave/${draft.slug}/`,enUrl:`/publications/${draft.slug}/`,publicUrl:`/objave/${draft.slug}/`,wordCountHr:words(draft.bodyHr),wordCountEn:words(draft.bodyEn),seo:{...draft.seo,canonical,author:AUTHOR}};const approved=await readList(env,'publish:approved');const articles=await readList(env,'data:articles:items');const news=await readList(env,'data:news:items');await writeList(env,'publish:approved',[article,...approved.filter(item=>item.slug!==article.slug)],500);await writeList(env,'data:articles:items',[article,...articles.filter(item=>item.slug!==article.slug)],500);await writeList(env,'data:news:items',[{id:`news-${article.id}`,kind:'news',title:article.titleHr,summary:article.summaryHr,url:canonical,sourceUrl:canonical,source:'GNK ASG Editorial Center',category:article.category,group:article.category,region:article.region,image:article.image,publishedAt:now,published_at:now,status:'published'},...news.filter(item=>item.url!==canonical)],500);await writeJson(env,`article:${article.id}`,article);await writeList(env,'editorial:published-history',[{articleId:article.id,draftId:draft.id,slug:article.slug,title:article.titleHr,publishedAt:now},...await readList(env,'editorial:published-history')],1000);await writeList(env,'editorial:drafts',drafts.filter(item=>item.id!==id),500);return{ok:true,article};}

export async function monitorPublications(env){const approved=await readList(env,'publish:approved');const drafts=await listDrafts(env);const sources=await readJson(env,'editorial:sources:last',null);const latest=approved[0]||null;const latestTime=Date.parse(latest?.publishedAt||latest?.published_at||'');const ageHours=Number.isFinite(latestTime)?Math.round((Date.now()-latestTime)/360000)/10:null;const status=!latest?'NO_PUBLICATIONS':ageHours>24?'WARNING_NO_PUBLICATION_24H':'OK';const result={ok:status==='OK',status,checkedAt:nowIso(),cadence:'every 2 hours',draftCount:drafts.length,publishedCount:approved.length,latestPublication:latest?{id:latest.id,slug:latest.slug,title:latest.titleHr||latest.title,publishedAt:latest.publishedAt||latest.published_at,ageHours}:null,sourceStatus:sources?{updatedAt:sources.updatedAt,count:sources.count,healthySources:sources.healthySources,totalSources:sources.totalSources}:null};await writeJson(env,'editorial:monitor:last',result);return result;}

export async function editorialStatus(env){const [drafts,published,sources,monitor,schedule]=await Promise.all([listDrafts(env),readList(env,'publish:approved'),readJson(env,'editorial:sources:last',null),readJson(env,'editorial:monitor:last',null),readJson(env,'editorial:schedule:last',null)]);return{ok:true,version:EDITORIAL_VERSION,sourceVersion:EDITORIAL_SOURCE_VERSION,schedule:{sourcePull:'09:00 and 16:00 Europe/Zagreb',publicationMonitor:'every 2 hours',publicationMode:'draft then manual publish'},drafts:drafts.slice(0,50),recentPublications:published.slice(0,20),sources:sources||{sources:EDITORIAL_SOURCES.map(source=>({...source,feeds:undefined}))},monitor,scheduleState:schedule};}

export async function scheduleLock(env,key,ttl=10800){const kv=store(env);if(!kv)return true;const current=await kv.get(key);if(current)return false;await kv.put(key,nowIso(),{expirationTtl:ttl});return true;}
export async function writeScheduleResult(env,result){return writeJson(env,'editorial:schedule:last',result);}
export { readJson, writeJson, readList, writeList, words };
