export const VERSION='GNK_ASG_MEDIA_SMS_V1_20260626_DRY_RUN';
const API='/api/media-command-center';
const STATUS_PATH=`${API}/sms-status`;
const PREVIEW_PATH=`${API}/sms-preview`;
const TEST_PATH=`${API}/sms-test`;
const SEND_PATH=`${API}/sms-send-application`;
const MAX_TEXT=480;
const clean=value=>String(value??'').trim();
const now=()=>new Date().toISOString();
const dbOf=env=>env.GNK_ASG_D1||null;
const boolEnv=value=>/^(1|true|yes|on)$/i.test(clean(value));
const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store, no-cache, must-revalidate, max-age=0','x-gnk-asg-media-sms':VERSION}});
function normalizePhone(value){const digits=clean(value).replace(/[^\d+]/g,'');if(!digits)return'';if(digits.startsWith('+'))return`+${digits.slice(1).replace(/\D/g,'')}`;if(digits.startsWith('00'))return`+${digits.slice(2).replace(/\D/g,'')}`;if(digits.startsWith('0'))return`+385${digits.slice(1).replace(/\D/g,'')}`;return`+${digits.replace(/\D/g,'')}`;}
function validPhone(value){return /^\+[1-9]\d{7,14}$/.test(normalizePhone(value));}
function allowlist(env){return new Set(clean(env.MEDIA_SMS_TEST_RECIPIENTS).split(/[;,\s]+/).map(normalizePhone).filter(validPhone));}
function providerConfigured(env){return Boolean(clean(env.MEDIA_SMS_PROVIDER_URL)&&clean(env.MEDIA_SMS_API_TOKEN)&&clean(env.MEDIA_SMS_FROM));}
function providerName(env){return clean(env.MEDIA_SMS_PROVIDER)||'generic-webhook';}
async function ensureSchema(env){const db=dbOf(env);if(!db)throw new Error('GNK_ASG_D1 binding is not configured');await db.prepare(`CREATE TABLE IF NOT EXISTS media_sms_attempts(id TEXT PRIMARY KEY,application_id TEXT,recipient TEXT NOT NULL,template TEXT,language TEXT,mode TEXT NOT NULL,status TEXT NOT NULL,provider TEXT,provider_message_id TEXT,error_code TEXT,text_body TEXT NOT NULL,detail_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,sent_at TEXT)`).run();await db.prepare(`CREATE INDEX IF NOT EXISTS idx_media_sms_attempts_created ON media_sms_attempts(created_at)`).run();return db;}
async function applicationById(env,id){const db=await ensureSchema(env);return db.prepare(`SELECT application_id,outlet_name,applicant_name,applicant_mobile,editor_name,editor_mobile,status,human_decision,decision_reason FROM media_applications WHERE application_id=?`).bind(clean(id)).first();}
function templateText(template,language,application={}){const hr=clean(language).toLowerCase()!=='en';const outlet=clean(application.outlet_name)||(hr?'vaša redakcija':'your newsroom');const name=clean(application.applicant_name)||clean(application.editor_name)||'';const hello=hr?(name?`Poštovani ${name},`:'Poštovani,'):(name?`Dear ${name},`:'Dear Applicant,');const ref=clean(application.application_id);const suffix=ref?(hr?` Referenca: ${ref}.`:` Reference: ${ref}.`):'';const map={received:hr?`${hello} GNK ASG je zaprimio prijavu redakcije ${outlet}. Slijedi provjera potpunosti i dokumenata.${suffix}`:`${hello} GNK ASG has received the application from ${outlet}. Completeness and document checks will follow.${suffix}`,missing:hr?`${hello} za prijavu redakcije ${outlet} potrebna je dopuna podataka ili dokumenata. Provjerite e-mail s detaljima.${suffix}`:`${hello} the application from ${outlet} requires additional information or documents. Please check the detailed email.${suffix}`,approved:hr?`${hello} prijava redakcije ${outlet} odobrena je nakon ljudske provjere. Daljnje upute stižu e-mailom.${suffix}`:`${hello} the application from ${outlet} was approved after human review. Further instructions will follow by email.${suffix}`,rejected:hr?`${hello} prijava redakcije ${outlet} nije odobrena nakon ljudske provjere. Obrazloženje je poslano e-mailom.${suffix}`:`${hello} the application from ${outlet} was not approved after human review. The explanation was sent by email.${suffix}`,reminder:hr?`${hello} podsjetnik: rok za dostavu potpune prijave i dokumenata je 20. 7. 2026. u 23:59 CEST.${suffix}`:`${hello} reminder: the deadline for a complete application and documents is 20 July 2026 at 23:59 CEST.${suffix}`};return clean(map[template]||map.received).slice(0,MAX_TEXT);}
async function buildMessage(env,body={}){const applicationId=clean(body.applicationId);const application=applicationId?await applicationById(env,applicationId):null;if(applicationId&&!application)return{ok:false,error:'application_not_found',status:404};const recipient=normalizePhone(body.recipient||application?.applicant_mobile||application?.editor_mobile);if(!validPhone(recipient))return{ok:false,error:'valid_recipient_required',status:400};const language=clean(body.language).toLowerCase()==='en'?'en':'hr';const template=clean(body.template)||'received';const text=clean(body.text)||templateText(template,language,application||{application_id:applicationId});if(!text)return{ok:false,error:'sms_text_required',status:400};if(text.length>MAX_TEXT)return{ok:false,error:'sms_text_too_long',status:400,maxCharacters:MAX_TEXT,actualCharacters:text.length};return{ok:true,application,applicationId,recipient,language,template,text,characters:text.length,segments:Math.max(1,Math.ceil(text.length/160))};}
async function providerSend(env,message,mode){if(!providerConfigured(env))throw Object.assign(new Error('SMS provider is not configured'),{code:'SMS_PROVIDER_NOT_CONFIGURED'});const response=await fetch(clean(env.MEDIA_SMS_PROVIDER_URL),{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${clean(env.MEDIA_SMS_API_TOKEN)}`,'x-gnk-asg-sms-version':VERSION},body:JSON.stringify({to:message.recipient,from:clean(env.MEDIA_SMS_FROM),text:message.text,clientReference:message.applicationId||crypto.randomUUID(),mode,metadata:{applicationId:message.applicationId||null,template:message.template,language:message.language}})});const raw=await response.text();let data={};try{data=JSON.parse(raw)}catch{data={raw:raw.slice(0,500)}}if(!response.ok)throw Object.assign(new Error(data.message||data.error||`SMS_PROVIDER_HTTP_${response.status}`),{code:data.code||`SMS_PROVIDER_HTTP_${response.status}`,detail:data});return{messageId:clean(data.messageId||data.id||data.sid),provider:providerName(env),detail:data};}
async function record(env,message,mode,status,detail={}){const db=await ensureSchema(env),id=crypto.randomUUID(),stamp=now();await db.prepare(`INSERT INTO media_sms_attempts(id,application_id,recipient,template,language,mode,status,provider,provider_message_id,error_code,text_body,detail_json,created_at,updated_at,sent_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,message.applicationId||'',message.recipient,message.template,message.language,mode,status,providerName(env),clean(detail.messageId),clean(detail.errorCode),message.text,JSON.stringify(detail),stamp,stamp,status==='SENT'?stamp:null).run();return id;}
async function status(env){let counts={},recent=[];try{const db=await ensureSchema(env);const rows=(await db.prepare(`SELECT status,COUNT(*) AS count FROM media_sms_attempts GROUP BY status`).all()).results||[];counts=Object.fromEntries(rows.map(row=>[row.status,Number(row.count)]));recent=(await db.prepare(`SELECT application_id,recipient,template,mode,status,provider_message_id,error_code,updated_at,sent_at FROM media_sms_attempts ORDER BY updated_at DESC LIMIT 20`).all()).results||[];}catch(error){return{ok:false,error:String(error?.message||error),version:VERSION};}return{ok:true,version:VERSION,provider:providerName(env),providerConfigured:providerConfigured(env),senderConfigured:Boolean(clean(env.MEDIA_SMS_FROM)),testLive:boolEnv(env.MEDIA_SMS_TEST_LIVE),live:boolEnv(env.MEDIA_SMS_LIVE),allowlistedTestRecipients:allowlist(env).size,maxCharacters:MAX_TEXT,counts,recent};}
async function preview(request,env){let body={};try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}const message=await buildMessage(env,body);if(!message.ok)return json(message,message.status||400);return json({ok:true,dryRun:true,version:VERSION,message:{applicationId:message.applicationId,recipient:message.recipient,language:message.language,template:message.template,text:message.text,characters:message.characters,segments:message.segments}});}
async function sendTest(request,env){let body={};try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}if(clean(body.confirm)!=='SEND_TEST_SMS')return json({ok:false,error:'confirmation_required',required:'SEND_TEST_SMS'},409);if(!boolEnv(env.MEDIA_SMS_TEST_LIVE))return json({ok:false,error:'test_sms_locked'},423);const message=await buildMessage(env,{...body,applicationId:'',template:body.template||'received'});if(!message.ok)return json(message,message.status||400);if(!allowlist(env).has(message.recipient))return json({ok:false,error:'recipient_not_allowlisted',configuredCount:allowlist(env).size},403);try{const result=await providerSend(env,message,'TEST');const id=await record(env,message,'TEST','SENT',result);return json({ok:true,live:true,test:true,id,delivery:result,message:{recipient:message.recipient,text:message.text,segments:message.segments}});}catch(error){const detail={errorCode:clean(error?.code)||'SMS_SEND_FAILED',message:String(error?.message||error).slice(0,500),providerDetail:error?.detail||null};const id=await record(env,message,'TEST','FAILED',detail);return json({ok:false,error:'test_sms_failed',id,...detail},502);}}
async function sendApplication(request,env){let body={};try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}if(clean(body.confirm)!=='SEND_APPLICATION_SMS')return json({ok:false,error:'confirmation_required',required:'SEND_APPLICATION_SMS'},409);if(!boolEnv(env.MEDIA_SMS_LIVE))return json({ok:false,error:'production_sms_locked'},423);const message=await buildMessage(env,body);if(!message.ok)return json(message,message.status||400);if(!message.applicationId)return json({ok:false,error:'application_id_required'},400);if(!['APPROVED','REJECTED','VERIFIED','REQUEST_MORE_INFORMATION'].includes(clean(message.application?.human_decision)))return json({ok:false,error:'human_decision_required',humanDecision:message.application?.human_decision||'PENDING'},409);try{const result=await providerSend(env,message,'PRODUCTION');const id=await record(env,message,'PRODUCTION','SENT',result);return json({ok:true,live:true,id,delivery:result,message:{applicationId:message.applicationId,recipient:message.recipient,text:message.text,segments:message.segments}});}catch(error){const detail={errorCode:clean(error?.code)||'SMS_SEND_FAILED',message:String(error?.message||error).slice(0,500),providerDetail:error?.detail||null};const id=await record(env,message,'PRODUCTION','FAILED',detail);return json({ok:false,error:'sms_send_failed',id,...detail},502);}}
export async function getMediaSmsStatus(env){return status(env);}
export async function handleMediaSms(request,env){const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';if(path===STATUS_PATH&&request.method==='GET')return json(await status(env));if(path===PREVIEW_PATH&&request.method==='POST')return preview(request,env);if(path===TEST_PATH&&request.method==='POST')return sendTest(request,env);if(path===SEND_PATH&&request.method==='POST')return sendApplication(request,env);return null;}
