name = "gnk-asg-media-trip-preview"
main = "src/index.js"
compatibility_date = "2026-06-21"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "GNK_ASG_KV"
id = "a3e9e78c7d554d7fa10996da9a89e7bc"

[[r2_buckets]]
binding = "GNK_ASG_MEDIA_ASSETS"
bucket_name = "gnk-asg-media-assets"
