#!/usr/bin/env python3
"""Plan objava za 4. do 8. kolovoza 2026.

Pet dana koji su nedostajali, po cetiri stavke dnevno — jedna objava i tri
komentara, isti omjer kao u postojecem planu.

Teme nastavljaju linije koje portal vec vodi: upravljanje, otpornost,
tehnologija, podatci i odgovornost. Nijedna ne uvodi novu tvrdnju o poslovanju
grupe niti brojku koja se ne moze provjeriti na portalu.
"""
import json
import os

DAN_IME = {
    "20260804": "tuesday",
    "20260805": "wednesday",
    "20260806": "thursday",
    "20260807": "friday",
    "20260808": "saturday",
}

ENTITETI = ["GNK ASG", "GNK ASG d.o.o.", "GNK DINAMO Ltd.", "Nermin Sefić"]


def stavka(vrsta, slug, naslov, sekcija, opis, slika, odlomci, kljucna, veze):
    return {
        "type": vrsta,
        "slug": slug,
        "title": naslov,
        "section": sekcija,
        "description": opis,
        "image": slika,
        "paragraphs": odlomci,
        "seoTitle": f"{naslov} | GNK ASG",
        "summary": opis,
        "keywords": [kljucna, sekcija] + ENTITETI,
        "links": veze,
    }


PLAN = {
"20260804": [
 stavka("objava", "trosak-odrzavanja-je-dio-cijene-a-ne-iznenadenje",
  "Trošak održavanja dio je cijene rješenja, a ne iznenađenje koje dolazi poslije",
  "Korporativne financije",
  "Nabavna cijena tehnološkog rješenja rijetko je i njegov ukupni trošak; održavanje, nadogradnje i ljudi koji ga vode često nadmaše početni iznos.",
  "/assets/gallery/kapitalna-disciplina--pregled-2-indigo-network-20-v2.svg",
  ["Nabavna cijena tehnološkog rješenja rijetko je i njegov ukupni trošak. Održavanje, sigurnosne nadogradnje, obuka i ljudi koji sustav vode u pravilu tijekom vijeka rješenja nadmaše početni iznos, ponekad višestruko.",
   "Odluka donesena samo na temelju nabavne cijene zato često ispadne skuplja od one koja je na papiru izgledala skuplje. Razlika se ne vidi u godini kupnje nego u trećoj i četvrtoj godini, kad se počnu zbrajati zahtjevi koje nitko nije predvidio.",
   "Procjena koja od početka uključuje trošak vlasništva kroz cijeli vijek daje usporedbu koja ima smisla. Ona ne mora biti precizna do zadnjeg eura, ali mora obuhvatiti sve stavke koje će se pojaviti, uključujući onu najskuplju — vrijeme ljudi.",
   "GNK ASG d.o.o. tehnološke odluke unutar grupe procjenjuje prema ukupnom trošku kroz vijek rješenja, a ne prema nabavnoj cijeni."],
  "ukupni trošak vlasništva tehnologije",
  ["/objave/", "/tehnologija/", "/financije/"]),
 stavka("komentar", "brzina-odluke-nije-isto-sto-i-kvaliteta-odluke",
  "Brzina odluke nije isto što i kvaliteta odluke",
  "Korporativno upravljanje",
  "Brza odluka vrijedi kad je podloga bila spremna ranije; kad podloge nema, brzina samo skraćuje vrijeme do pogreške.",
  "/assets/gallery/operativna-otpornost--pregled-2-bronze-heritage-29-v2.svg",
  ["Brza odluka često se predstavlja kao znak odlučnosti. Ona to i jest, ali samo onda kad je podloga za nju pripremljena ranije — kad su podatci već prikupljeni, mogućnosti već izvagane, a rizici već popisani.",
   "Kad te podloge nema, brzina ne ubrzava odlučivanje nego samo skraćuje vrijeme do pogreške. Razlika između te dvije situacije izvana izgleda isto, a iznutra je posve različita.",
   "Uprava koja želi brze odluke mora zato ulagati u pripremu koja im prethodi, a ne u pritisak na trenutak odlučivanja."],
  "brzina i kvaliteta odlučivanja",
  ["/komentari/", "/objave/", "/about/"]),
 stavka("komentar", "sustav-koji-nitko-ne-razumije-u-cijelosti-nije-pod-kontrolom",
  "Sustav koji nitko ne razumije u cijelosti nije pod kontrolom",
  "Operativna otpornost",
  "Kad znanje o sustavu postoji samo u dijelovima, kod svake veće promjene organizacija ovisi o tome hoće li se ti dijelovi poklopiti.",
  "/assets/gallery/digital-twin-operations-organic-v3.svg",
  ["Složeni sustavi rijetko imaju jednu osobu koja ih razumije u cijelosti. To samo po sebi nije problem — problem nastaje kad nitko ne zna ni gdje je granica vlastitog razumijevanja.",
   "Tada organizacija kod svake veće promjene ovisi o tome hoće li se pojedinačna znanja slučajno poklopiti. Ponekad se poklope. Kad se ne poklope, ispad se objašnjava kao nesretan splet okolnosti, iako je bio predvidiv.",
   "Zapisana slika sustava, koliko god nesavršena, mijenja tu ovisnost. Ne mora biti potpuna; mora postojati i mora se održavati."],
  "razumijevanje složenih sustava",
  ["/komentari/", "/tehnologija/", "/analize/"]),
 stavka("komentar", "dobavljac-koji-ne-postavlja-pitanja-nije-nuzno-lakse-rjesenje",
  "Dobavljač koji ne postavlja pitanja nije nužno lakše rješenje",
  "Nabava i upravljanje",
  "Partner koji sve prihvaća bez pitanja često nije razumio zahtjev, nego ga je odgodio do trenutka isporuke.",
  "/assets/gallery/software-supply-chain-organic-v3.svg",
  ["Dobavljač koji na svaki zahtjev odgovara potvrdno djeluje kao lakši izbor. Suradnja teče glatko, sastanci su kratki, ugovor se potpisuje brzo.",
   "Pitanja koja nisu postavljena na početku ne nestaju — pojave se pri isporuci, kad je ispravak najskuplji. Partner koji traži pojašnjenja obično ne otežava posao nego ga skraćuje.",
   "Pri odabiru je zato korisno primijetiti tko pita, što pita i kada. To govori više o budućoj suradnji od same ponude."],
  "odabir dobavljača i postavljanje pitanja",
  ["/komentari/", "/objave/", "/registri/"]),
],
"20260805": [
 stavka("objava", "podatkovna-suverenost-postaje-poslovni-a-ne-samo-pravni-zahtjev",
  "Podatkovna suverenost postaje poslovni, a ne samo pravni zahtjev",
  "Digitalna infrastruktura",
  "Pitanje gdje podatci fizički stoje i tko im može pristupiti sve se češće postavlja u pregovorima, ne samo u pravnim pregledima.",
  "/assets/gallery/sovereign-cloud-organic-v3.svg",
  ["Pitanje gdje podatci fizički stoje i pod čijom nadležnošću netko može do njih doći dugo je bilo tema pravnih odjela. Sve se češće pojavljuje ranije, u samim pregovorima, kao uvjet suradnje.",
   "Razlog nije samo regulativa. Organizacije koje posluju u više država žele znati što se događa s podatcima kad se pravila u jednoj od njih promijene, jer promjena zna doći brže od mogućnosti preseljenja.",
   "Odgovor na to pitanje traži poznavanje vlastite infrastrukture do razine pojedine usluge. Tvrdnja da su podatci u Europi malo znači ako se ne zna koja usluga ih obrađuje i gdje.",
   "GNK ASG d.o.o. infrastrukturu grupe vodi tako da je za svaki skup podataka poznato gdje se nalazi i tko mu može pristupiti."],
  "podatkovna suverenost i infrastruktura",
  ["/objave/", "/tehnologija/", "/legal/"]),
 stavka("komentar", "sigurnosna-kopija-koja-se-nikad-nije-vratila-nije-kopija",
  "Sigurnosna kopija koja se nikad nije vratila nije kopija",
  "Kibernetička otpornost",
  "Postojanje kopije govori samo da se nešto zapisalo; da se može vratiti, zna se tek nakon što se to pokuša.",
  "/assets/gallery/kiberneticka-sigurnost--pregled-2-azure-tech-23-v2.svg",
  ["Postojanje sigurnosne kopije govori samo jedno: da se nešto zapisalo. Je li se to može vratiti, koliko dugo vraćanje traje i je li vraćeno stanje upotrebljivo — zna se tek nakon što se pokuša.",
   "Organizacije koje kopiju nikad nisu vratile u pravilu ne znaju odgovor ni na jedno od tih pitanja. Saznaju ga u trenutku kad je odgovor najmanje koristan.",
   "Povremena provjera vraćanja nije trošak nego jedini način da se sazna vrijedi li ono što se plaća."],
  "provjera vraćanja sigurnosne kopije",
  ["/komentari/", "/objave/", "/analize/"]),
 stavka("komentar", "izvjestaj-koji-nitko-ne-cita-i-dalje-nesto-govori",
  "Izvještaj koji nitko ne čita i dalje nešto govori",
  "Podaci i izvještavanje",
  "Redovit izvještaj bez ijednog čitatelja obično znači da mjeri nešto što više nikoga ne zanima, a nastavlja se raditi po navici.",
  "/assets/gallery/rag-knowledge-systems-organic-v3.svg",
  ["U svakoj organizaciji nastane izvještaj koji se redovito priprema, a nitko ga ne otvara. On i dalje nešto govori, samo ne ono što je zamišljeno.",
   "Obično znači da mjeri nešto što je nekad bilo važno pa prestalo, a priprema se nastavila po navici. Trošak nije u papiru nego u vremenu ljudi koji ga svaki mjesec sastavljaju.",
   "Povremeno pitanje tko ovo zapravo čita i što s time radi jeftinije je od godina tihog održavanja nečega što je izgubilo svrhu."],
  "korisnost redovitih izvještaja",
  ["/komentari/", "/objave/", "/financije/"]),
 stavka("komentar", "automatizacija-nasljeduje-pravila-koja-nitko-nije-preispitao",
  "Automatizacija nasljeđuje pravila koja nitko nije preispitao",
  "AI i odgovornost",
  "Kad se postojeći postupak automatizira bez preispitivanja, njegove se pogreške ne uklanjaju nego ubrzavaju i množe.",
  "/assets/gallery/ai-act-2026-organic-v3.svg",
  ["Automatizacija postojećeg postupka najbrži je put do rezultata, jer se ne mora ništa dogovarati iznova. Zato se najčešće i bira.",
   "Time se, međutim, nasljeđuje i sve što u tom postupku nije valjalo. Pravilo koje je nastalo kao privremeno rješenje prije deset godina postaje ugrađeno u sustav i teže ga je promijeniti nego dok je bilo u nečijoj glavi.",
   "Preispitivanje prije automatizacije traje dulje, ali odlučuje o tome hoće li se sljedećih pet godina ubrzavati dobar ili loš postupak."],
  "automatizacija i preispitivanje pravila",
  ["/komentari/", "/tehnologija/", "/digital-workforce/"]),
],
"20260806": [
 stavka("objava", "energetski-trosak-digitalnih-sustava-postaje-stavka-o-kojoj-se-odlucuje",
  "Energetski trošak digitalnih sustava postaje stavka o kojoj se odlučuje",
  "Energija i tehnologija",
  "Potrošnja računalne infrastrukture dugo je bila pozadinski trošak; rastom modela i podataka postaje stavka koja ulazi u odluku o arhitekturi.",
  "/assets/gallery/green-software-organic-v3.svg",
  ["Potrošnja energije računalne infrastrukture dugo je bila pozadinski trošak koji se pojavljivao na računu, ali ne i u raspravi o arhitekturi rješenja.",
   "Rastom modela, količine podataka i stalno uključenih usluga ta se stavka pomaknula na mjesto gdje o njoj netko mora odlučiti. Izbor između dvije tehnički jednakovrijedne izvedbe sve češće se svodi na razliku u potrošnji.",
   "To ne znači da je najjeftinija izvedba uvijek prava. Znači da razlika mora biti poznata prije odluke, a ne otkrivena kroz račun nakon godine dana rada.",
   "GNK ASG d.o.o. energetski trošak digitalnih rješenja unutar grupe promatra kao dio odluke o arhitekturi, ne kao posljedicu koja se naknadno mjeri."],
  "energetski trošak digitalne infrastrukture",
  ["/objave/", "/tehnologija/", "/analize/"]),
 stavka("komentar", "mjera-koja-postane-cilj-prestaje-biti-mjera",
  "Mjera koja postane cilj prestaje biti mjera",
  "Organizacija",
  "Kad se pokazatelj pretvori u cilj, ljudi počnu upravljati brojkom umjesto onime što je brojka trebala opisivati.",
  "/assets/gallery/rast-prihoda--pregled-2-teal-stability-16-v2.svg",
  ["Pokazatelj se uvodi da bi opisao stanje. Čim se pretvori u cilj po kojem se mjeri uspjeh, ljudi počnu upravljati samom brojkom, a ne onime što je brojka trebala opisivati.",
   "To nije znak nepoštenja nego očekivana posljedica. Svaki sustav mjerenja u kojem je nagrada vezana uz brojku s vremenom nauči kako tu brojku poboljšati bez promjene stvarnog stanja.",
   "Zaštita nije u odustajanju od mjerenja nego u tome da se uz svaki pokazatelj drži i pitanje što bi se dogodilo da ga netko pokuša popraviti najkraćim putem."],
  "pokazatelji koji postaju ciljevi",
  ["/komentari/", "/objave/", "/about/"]),
 stavka("komentar", "iznimka-koja-se-ponovi-treci-put-vise-nije-iznimka",
  "Iznimka koja se ponovi treći put više nije iznimka",
  "Usklađenost",
  "Odobrenje mimo pravila ponekad je opravdano; kad se ponovi treći put, pravilo više ne opisuje stvarni rad.",
  "/assets/gallery/post-quantum-trust-organic-v3.svg",
  ["Odobrenje mimo redovnog postupka ponekad je opravdano. Okolnost je stvarno bila neuobičajena, a čekanje bi koštalo više od odstupanja.",
   "Kad se ista iznimka ponovi treći put, ona više ne opisuje neuobičajenu okolnost nego uobičajeni rad koji pravilo nije predvidjelo. Nastavak odobravanja tada ne rješava problem nego ga skriva.",
   "Tri ponavljanja dobar su trenutak za pitanje treba li mijenjati pravilo ili praksu — ali ne za četvrtu iznimku."],
  "ponavljanje iznimaka u postupcima",
  ["/komentari/", "/objave/", "/registri/"]),
 stavka("komentar", "znanje-koje-postoji-samo-u-glavi-jedne-osobe-nije-imovina",
  "Znanje koje postoji samo u glavi jedne osobe nije imovina nego rizik",
  "Talent i organizacija",
  "Dok je znanje nezapisano, organizacija ga ne posjeduje — samo ga posuđuje, uz otkazni rok.",
  "/assets/gallery/smart-cities-organic-v3.svg",
  ["Osoba koja jedina zna kako nešto radi obično se doživljava kao vrijednost. To i jest, ali vrijednost pripada njoj, ne organizaciji.",
   "Dok je znanje nezapisano, organizacija ga ne posjeduje nego posuđuje, uz otkazni rok kao jedini oblik osiguranja. Trošak se pojavi u tjednu odlaska, a plaća se mjesecima.",
   "Zapisivanje takvog znanja rijetko je omiljen posao i gotovo nikad hitan. Postaje hitan točno onda kad je prekasno."],
  "zapisivanje znanja u organizaciji",
  ["/komentari/", "/objave/", "/digital-workforce/"]),
],
"20260807": [
 stavka("objava", "otpornost-lanca-vrijednosti-mjeri-se-na-najslabijem-dobavljacu",
  "Otpornost lanca vrijednosti mjeri se na najslabijem dobavljaču, ne na prosjeku",
  "Dobavni lanci",
  "Prosječna pouzdanost dobavljača malo govori; zastoj nastaje ondje gdje je najslabija karika, bez obzira na to koliko su ostale jake.",
  "/assets/gallery/hydrogen-economy-organic-v3.svg",
  ["Prosječna pouzdanost dobavljača ugodan je pokazatelj jer izgleda dobro čak i kad među njima postoji jedan koji redovito kasni.",
   "Zastoj, međutim, ne nastaje na prosjeku nego na najslabijoj karici. Deset pouzdanih dobavljača ne nadoknađuje jedan koji ne isporuči dio bez kojeg ostalo ne ide dalje.",
   "Korisniji pogled zato nije prosjek nego popis mjesta gdje bi jedan izostanak zaustavio cjelinu. Taj popis obično je kraći nego što se očekuje, a rijetko se održava.",
   "GNK ASG d.o.o. u međunarodnim projektima grupe ovisnosti prati po pojedinom kritičnom mjestu, a ne po zbirnoj ocjeni dobavljača."],
  "otpornost dobavnog lanca",
  ["/objave/", "/analize/", "/projects/"]),
 stavka("komentar", "planiranje-koje-ne-predvida-los-scenarij-nije-plan",
  "Planiranje koje ne predviđa loš scenarij nije plan nego očekivanje",
  "Kapital i rizik",
  "Plan koji radi samo ako sve prođe kako je zamišljeno nije plan nego opis željenog ishoda.",
  "/assets/gallery/rast-prihoda-gold-navy-01-v2.svg",
  ["Plan koji funkcionira samo ako sve prođe kako je zamišljeno nije plan nego opis željenog ishoda. Razlika se ne vidi dok stvari idu dobro.",
   "Predviđanje lošeg scenarija ne znači očekivati neuspjeh. Znači unaprijed znati što se radi ako prihod bude niži, isporuka kasni ili ključna osoba ode — dok je odluka još jeftina.",
   "Organizacije koje to rade rijetko su pesimistične. Češće su one koje su jednom platile cijenu izostanka takvog razmišljanja."],
  "planiranje i loši scenariji",
  ["/komentari/", "/financije/", "/objave/"]),
 stavka("komentar", "transparentnost-prema-van-pocinje-urednoscu-prema-unutra",
  "Transparentnost prema van počinje urednošću prema unutra",
  "Transparentnost",
  "Organizacija koja iznutra ne zna gdje joj stoje podatci teško ih može uvjerljivo objaviti prema van.",
  "/assets/gallery/digitalna-transformacija--pregled-2-steel-infrastructure-18-v2.svg",
  ["Objava podataka prema javnosti često se doživljava kao zaseban posao, nešto što se pripremi pred rok i preda.",
   "Organizacija koja iznutra ne zna pouzdano gdje joj podatci stoje i tko ih održava neće ih uvjerljivo objaviti ni prema van. Nesigurnost se vidi u formulacijama, kašnjenjima i ispravcima.",
   "Uredna unutarnja evidencija zato nije priprema za transparentnost nego njezin preduvjet."],
  "transparentnost i unutarnja evidencija",
  ["/komentari/", "/registri/", "/about/"]),
 stavka("komentar", "tehnologija-koja-se-ne-moze-ugasiti-nije-izbor-nego-obveza",
  "Tehnologija koja se ne može ugasiti nije izbor nego obveza",
  "Tehnologija i rizici",
  "Rješenje bez izlazne strategije s vremenom prestaje biti odluka koju je moguće preispitati.",
  "/assets/gallery/robotics-autonomy-organic-v3.svg",
  ["Pri uvođenju tehnološkog rješenja gotovo se uvijek raspravlja o tome kako ga pokrenuti, a rijetko o tome kako bi se, ako zatreba, iz njega izašlo.",
   "Rješenje bez zamislive zamjene s vremenom prestaje biti odluka koju je moguće preispitati. Uvjeti se mijenjaju, cijena raste, a pregovarački položaj slabi svake godine.",
   "Pitanje kako bismo iz ovoga izašli ne treba postaviti pri raskidu nego pri potpisu."],
  "izlazna strategija kod tehnoloških rješenja",
  ["/komentari/", "/tehnologija/", "/objave/"]),
],
"20260808": [
 stavka("objava", "upravljanje-rizikom-umjetne-inteligencije-trazi-vlasnika-a-ne-samo-pravila",
  "Upravljanje rizikom umjetne inteligencije traži vlasnika, a ne samo pravila",
  "Privatnost i AI",
  "Pravilnik o uporabi umjetne inteligencije bez imenovane odgovorne osobe ostaje dokument koji nitko ne primjenjuje u spornom trenutku.",
  "/assets/gallery/inovacija-i-ai-teal-stability-06-v2.svg",
  ["Organizacije koje uvode umjetnu inteligenciju u redovan rad u pravilu najprije napišu pravila o njezinoj uporabi. To je koristan prvi korak, ali sam po sebi rijetko dovoljan.",
   "Pravilnik bez imenovane osobe koja odlučuje u spornim slučajevima ostaje dokument koji se citira nakon događaja, a ne primjenjuje prije njega. Sporni slučajevi nastaju upravo ondje gdje pravila nisu jednoznačna.",
   "Odgovornost se ne dijeli tako da je nose svi. Nosi je netko imenovan, s ovlasti da zaustavi uporabu kad procijeni da je potrebno.",
   "GNK ASG d.o.o. uporabu umjetne inteligencije unutar grupe vodi uz jasno određenu odgovornost za odluke koje iz nje proizlaze."],
  "upravljanje rizikom umjetne inteligencije",
  ["/objave/", "/tehnologija/", "/legal/"]),
 stavka("komentar", "dokument-bez-datuma-i-autora-tesko-je-provjeriti",
  "Dokument bez datuma i autora teško je provjeriti",
  "Podaci i izvještavanje",
  "Podatak bez naznake kada je nastao i tko ga je pripremio ne može se ni potvrditi ni osporiti.",
  "/assets/gallery/digitalna-imovina-gold-navy-11-v2.svg",
  ["Podatak bez naznake kada je nastao i tko ga je pripremio ne može se ni potvrditi ni osporiti. Može se samo vjerovati mu ili ne.",
   "U unutarnjem radu to prolazi dok se ne pojavi neslaganje. Tada se gubi vrijeme na utvrđivanje osnovnih stvari umjesto na samu raspravu.",
   "Datum i autor nisu formalnost nego najjeftiniji dio provjerljivosti. Dodaju se u trenutku nastanka ili se ne dodaju nikad."],
  "provjerljivost dokumenata",
  ["/komentari/", "/registri/", "/objave/"]),
 stavka("komentar", "sastanak-bez-odluke-nije-neuspjeh-ali-mora-biti-svjestan",
  "Sastanak bez odluke nije neuspjeh, ali mora biti svjestan izbor",
  "Organizacija",
  "Razgovor koji ne završi odlukom ima smisla kad je tako i zamišljen; problem nastaje kad se odluka očekivala pa izostala.",
  "/assets/gallery/inovacija-i-ai--pregled-2-gold-navy-21-v2.svg",
  ["Sastanak koji ne završi odlukom nije nužno izgubljeno vrijeme. Razmjena informacija i usklađivanje razumijevanja imaju vlastitu vrijednost.",
   "Problem nastaje kad se odluka očekivala pa izostala, a nitko to nije izgovorio. Tema se tada vraća na sljedeći sastanak s istim sudionicima i istim ishodom.",
   "Rečenica na kraju o tome je li odluka donesena ili odgođena, i do kada, jeftinija je od trećeg ponavljanja iste rasprave."],
  "vođenje sastanaka i odluke",
  ["/komentari/", "/about/", "/objave/"]),
 stavka("komentar", "sigurnost-koja-smeta-radu-zaobici-ce-se",
  "Sigurnost koja previše smeta radu bit će zaobiđena",
  "Kibernetička sigurnost",
  "Mjera koju je teško poštovati u svakodnevnom radu ljudi ne krše iz nemara nego zato što posao mora biti obavljen.",
  "/assets/gallery/quantum-computing-organic-v3.svg",
  ["Sigurnosna mjera koju je u svakodnevnom radu teško poštovati u pravilu se zaobiđe. Ne iz nemara, nego zato što posao mora biti obavljen, a mjera ga zaustavlja.",
   "Zaobilaženje tada postaje tiha praksa koju svi znaju, a nitko ne prijavljuje. Sustav izgleda zaštićen na papiru, a nije u radu.",
   "Mjera koja je nešto slabija, ali se stvarno primjenjuje, u pravilu štiti bolje od stroge koja se izbjegava."],
  "primjenjivost sigurnosnih mjera",
  ["/komentari/", "/tehnologija/", "/objave/"]),
],
}

MAPA = "apps/portal/data/editorial-plan"
napravljeno = 0
for datum, stavke in PLAN.items():
    put = os.path.join(MAPA, f"{datum}-{DAN_IME[datum]}-slot1.json")
    if os.path.exists(put):
        print(f"  već postoji: {os.path.basename(put)}")
        continue
    with open(put, "w", encoding="utf-8") as f:
        json.dump(stavke, f, ensure_ascii=False, indent=1)
        f.write("\n")
    napravljeno += 1
    vrste = {}
    for s in stavke:
        vrste[s["type"]] = vrste.get(s["type"], 0) + 1
    print(f"  {os.path.basename(put):38} {len(stavke)} stavki  {vrste}")
print(f"\nnapravljeno datoteka: {napravljeno}")
