name = "gnk-asg-contact-api"
main = "src/index.js"
compatibility_date = "2026-06-17"
workers_dev = true

routes = [
  { pattern = "gnk-asg.hr/api/contact-submit*", zone_name = "gnk-asg.hr" },
  { pattern = "www.gnk-asg.hr/api/contact-submit*", zone_name = "gnk-asg.hr" }
]

[[kv_namespaces]]
binding = "GNK_ASG_CONFIG_KV"
id = "d6f5dac9fa034d8d813db0de44eb7b1b"

[[kv_namespaces]]
binding = "GNK_ASG_KV"
id = "a3e9e78c7d554d7fa10996da9a89e7bc"

[[r2_buckets]]
binding = "GNK_ASG_MEDIA_ASSETS"
bucket_name = "gnk-asg-media-assets"

[[d1_databases]]
binding = "GNK_ASG_D1"
database_name = "gnk_asg_operator_logs"
database_id = "2116c4e5-1850-4888-91e7-c47deead3ced"

[[send_email]]
name = "EMAIL"
destination_address = "rht@gmx.com"

