name = "gnk-asg-operator-center"
main = "src/index.js"
compatibility_date = "2026-06-13"
workers_dev = true
preview_urls = true

[assets]
directory = "../../apps/portal"
binding = "ASSETS"
run_worker_first = true
